import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import test from 'node:test'
import sharp from 'sharp'

const validator = new URL('./validate-post.mjs', import.meta.url)

async function fixture(body) {
  const root = await mkdtemp(path.join(os.tmpdir(), 'matthew-blog-skill-'))
  const directory = path.join(root, 'content/blog/agent-workflow')
  await mkdir(directory, { recursive: true })
  await mkdir(path.join(root, 'lib'), { recursive: true })
  await writeFile(path.join(directory, 'cover.webp'), await sharp({ create: { width: 16, height: 9, channels: 3, background: '#111' } }).webp().toBuffer())
  const frontmatter = `---\ntitle: "Title"\ndescription: "Description"\npublishedAt: "2026-08-10T00:00:00.000Z"\ncover: "./cover.webp"\ncoverWidth: 16\ncoverHeight: 9\n---\n`
  await writeFile(path.join(directory, 'index.mdx'), `${frontmatter}${body}`)
  await writeFile(path.join(directory, 'index.en.mdx'), `---\ntitle: "Title"\ndescription: "Description"\n---\n${body}`)
  await writeFile(path.join(directory, 'publication.json'), JSON.stringify({ media: { 'cover.webp': { source: 'Test fixture generated by Sharp', rights: 'generated' } }, manualChecks: [] }))
  await writeFile(path.join(root, 'lib/public-content-routes.ts'), 'export const publishedPostSlugs = []')
  await writeFile(path.join(root, 'lib/view-transition-name.ts'), 'export function id() {}')
  return root
}

function validate(root, ...flags) {
  return spawnSync(process.execPath, [validator.pathname, 'agent-workflow', '--draft', ...flags], { cwd: root, encoding: 'utf8' })
}

test('draft gate accepts checked local media, HTTPS links, and supported video embeds', async () => {
  const root = await fixture('[Source](https://example.com)\n\n![Diagram](./cover.webp#16x9 "Diagram")\n\n<VideoEmbed provider="youtube" id="dQw4w9WgXcQ" title="Demo" />')
  const result = validate(root)
  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /valid \(draft\)/)
})

test('draft gate rejects unsafe links, malformed identifiers, and raw embeds', async () => {
  const root = await fixture('[Insecure](http://example.com) [Script](javascript:alert(1))\n\n<VideoEmbed provider="vimeo" id="bad" title="Demo" />\n\n{process.env.SECRET}')
  const result = validate(root)
  assert.equal(result.status, 1)
  assert.match(result.stderr, /link must use HTTPS/)
  assert.match(result.stderr, /javascript:/)
  assert.match(result.stderr, /Invalid Vimeo video ID/)
  assert.match(result.stderr, /forbidden executable MDX/)
})

test('draft gate rejects orphaned media without provenance or an article reference', async () => {
  const root = await fixture('Draft body')
  await writeFile(path.join(root, 'content/blog/agent-workflow/orphan.webp'), await sharp({ create: { width: 2, height: 2, channels: 3, background: '#fff' } }).webp().toBuffer())
  const result = validate(root)
  assert.equal(result.status, 1)
  assert.match(result.stderr, /unreferenced media file must be removed/)
})

test('draft gate rejects active SVG instead of producing a broken public asset', async () => {
  const root = await fixture('![Diagram](./diagram.svg#10x10)')
  await writeFile(path.join(root, 'content/blog/agent-workflow/diagram.svg'), '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"/>')
  const result = validate(root)
  assert.equal(result.status, 1)
  assert.match(result.stderr, /unsupported SVG media/)
})

test('draft gate rejects a slug that is already publicly registered', async () => {
  const root = await fixture('Draft body')
  await writeFile(path.join(root, 'lib/public-content-routes.ts'), "export const publishedPostSlugs = ['agent-workflow']")
  const result = validate(root)
  assert.equal(result.status, 1)
  assert.match(result.stderr, /already exposed through a public registry/)
})

test('link gate accepts an auditable manual browser check when automation is blocked', async () => {
  const url = 'https://127.0.0.1:1/provider-blocked'
  const root = await fixture(`[Source](${url})`)
  const evidence = {
    media: { 'cover.webp': { source: 'Test fixture generated by Sharp', rights: 'generated' } },
    manualChecks: [{ url, checkedAt: '2026-08-09T00:00:00.000Z', note: 'Opened in a clean browser and confirmed the cited page.' }],
  }
  await writeFile(path.join(root, 'content/blog/agent-workflow/publication.json'), JSON.stringify(evidence))
  const result = validate(root, '--check-links')
  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stderr, /manual check accepted/)
})
