export const siteProfile = {
  name: {
    zh: '老苗',
    en: 'Matthew Miao',
    displayEn: 'Matthew',
  },
  email: 'hi@fengtalk.ai',
  domain: 'matthew-miao.com',
  copyright: {
    year: 2026,
    zh: '老苗 / Matthew Miao',
    en: 'Matthew Miao',
  },
  bio: {
    zh: 'Web coding、AI Agent、自动化、outreach 与企业知识系统。',
    en: 'Web coding, AI agents, automation, outreach, and company knowledge systems.',
  },
  location: {
    city: 'Brisbane',
    country: 'Australia',
    timeZone: 'Australia/Brisbane',
    utcLabel: 'UTC+10',
    latitude: '27.4698° S',
    longitude: '153.0251° E',
  },
  links: {
    githubUsername: 'matthew6688',
    fengtalk: 'https://fengtalk.ai',
    uchat: 'https://uchat.au',
    calcomBooking: 'https://cal.com/matthew-miao/ama',
    x: {
      handle: 'fengtalk_ai',
      url: 'https://x.com/fengtalk_ai',
    },
    wechatService: {
      searchName: 'matthewmiao',
      qrImage: '/images/social/wechat-service-matthewmiao.png',
    },
    wechatSubscription: {
      searchName: 'fengtalk.ai',
      qrImage: '/images/social/wechat-subscription-fengtalk.png',
    },
    youtube: null,
    telegram: null,
    xiaohongshu: null,
  },
  experience: [
    {
      company: 'UChat',
      companyEn: 'UChat',
      role: '首席营销官',
      roleEn: 'Chief Marketing Officer',
      from: 2020,
      url: 'https://uchat.au',
    },
  ],
  projects: [
    {
      slug: 'fengtalk',
      name: 'FengTalk.ai',
      nameEn: 'FengTalk.ai',
      description: '从海关数据和多渠道线索出发，将客户研究、触达与持续跟进连接成一套 AI 外贸获客流程。',
      descriptionEn: 'An AI-powered export growth workflow connecting trade data and multi-channel signals with research, outreach, and sustained follow-up.',
      url: 'https://fengtalk.ai',
      icon: '/images/projects/fengtalk.svg',
      cover: '/images/showcases/products/fengtalk-cover.svg',
      coverWidth: 600,
      coverHeight: 840,
      domain: 'fengtalk.ai',
      category: 'AI 外贸获客',
      categoryEn: 'AI export growth',
      status: 'live',
      shelfColor: '#ded7c9',
      shelfInk: '#171713',
    },
    {
      slug: 'tradescope',
      name: 'TradeScope 海关数据',
      nameEn: 'TradeScope Customs Data',
      description: '按产品或 HS 编码查看拉美 13 国的进口商、供应商、交易记录与开发优先级。',
      descriptionEn: 'Explore importers, suppliers, shipment records, and sales priorities across 13 Latin American markets by product or HS code.',
      url: 'https://fengtalk.ai/data',
      icon: '/images/projects/tradescope.svg',
      cover: '/images/showcases/products/tradescope-cover.svg',
      coverWidth: 600,
      coverHeight: 840,
      domain: 'fengtalk.ai/data',
      category: '海关数据产品',
      categoryEn: 'Customs data product',
      status: 'live',
      shelfColor: '#384238',
      shelfInk: '#f7f4ed',
    },
    {
      slug: 'fengreach',
      name: 'FengReach',
      nameEn: 'FengReach',
      description: '捕获 LinkedIn 线索，结合企业知识生成可审核的个性化开发信序列，再由人工批准发送。',
      descriptionEn: 'Turn LinkedIn leads and company knowledge into reviewable personalized outreach sequences, with human approval before sending.',
      url: 'https://reach.fengtalk.ai/zh/',
      icon: '/images/projects/fengreach.svg',
      cover: '/images/showcases/products/fengreach-cover.svg',
      coverWidth: 600,
      coverHeight: 840,
      domain: 'reach.fengtalk.ai',
      category: '销售外联 SaaS',
      categoryEn: 'Sales outreach SaaS',
      status: 'live',
      shelfColor: '#0b2b22',
      shelfInk: '#f0e8d8',
    },
  ],
  features: {
    personalShelves: false,
  },
} as const
